version: "2"
services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app:rw
      - /app/node_modules #ignore local node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    # links:
    #   - redis
    networks:
      - front-tier
      # - back-tier
    command: npm run dev

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   volumes:
  #     - ./data/redis:/data/redis
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - back-tier

networks:
  front-tier:
  # back-tier:
