version: "3"
services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app:rw
      - /app/node_modules #ignore local node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    links:
      - mongo_db
    #   - redis_db
    networks:
      - front-tier
      - back-tier
    command: npm run dev
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      #  Use this on windows system, db will be on Hyper-V drive
      #  located on C:Users/Public/Public Documents/Hyper-V/Virtual hard disks/DockerDesktop
      - mongodata:/data/db
      #  Can use this if on Linux based system
      # - ./tmp_data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - back-tier

  redis_db:
    image: redis:latest
    container_name: redis_db
    volumes:
      - ./tmp_data/redis:/data/redis
    ports:
      - 6379:6379
    networks:
      - back-tier

volumes:
  mongodata:
networks:
  front-tier:
  back-tier:
