version: "3"
services:
  h3nr7_web_v1:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app:rw
      - /app/node_modules #ignore local node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev

